accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView,HomeView, 
    UserLoginView, UserLogoutView,
    ProfileEditView,UserListView, 
)
from . import views # 追加

app_name = 'accounts'
urlpatterns = [
    #path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),  
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'), 
    path('userlist/', UserListView.as_view(), name='userlist'), 
    path('mk_relation/<int:pk>/', views.mk_relation, name='mk_relation'), # 追加
    path('rm_relation/<int:pk>/', views.rm_relation, name='rm_relation'), # 追加
]

microposts/urls.py
from django.urls import path
from .views import (
    PostCreateView, PostListView, 
    PostUpdateView, PostDeleteView,
    MyPostsView, 
    FollowersView, FollowingView,
    GalleryView,# 追加
)
from . import views 

app_name = 'microposts'
urlpatterns = [
    path('create/', PostCreateView.as_view(), name='create'),
    path('postlist/', PostListView.as_view(), name='postlist'), 
    path('update/<int:pk>', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='delete'),
    path('myposts/', MyPostsView.as_view(), name='myposts'),
    path('add_favourite/<int:pk>/', views.add_favourite, name='add_favourite'),
    path('rm_favourite/<int:pk>/', views.remove_favourite, name='rm_favourite'),
    path('follower/', FollowersView.as_view(), name='follower'), 
    path('following/', FollowingView.as_view(), name='following'), 
    path('gallery/', GalleryView.as_view(), name='gallery'), # 追加
    path('add_file/', views.add_file, name='add_file'), # 追加    
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加
from accounts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('microposts/', include('microposts.urls')), # 追加
    path('', HomeView.as_view(), name='home')
]

# mediaを使うために追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microposts/models.py
from django.db import models


class Post(models.Model):
    # Postのオーナーを設定する
    owner = models.ForeignKey('accounts.User', verbose_name='オーナー', on_delete=models.CASCADE)
    content = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(upload_to='images/',blank=True, null=True) # 追加

    class Meta:
        db_table = 'posts'

class Gallery(models.Model):
    # Imageのオーナーを設定する
    owner = models.ForeignKey('accounts.User', verbose_name='オーナー', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='gallery/') # 追加

    class Meta:
        db_table = 'gallery'

    def __str__(self):
        return str(self.pk)

microposts/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        # imageフィールドを追加
        fields = (
            'content','image' 
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30,
                'placeholder': 'ここに入力してください'}
            ),
        }


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content','image'
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30}
            ),
        }

microposts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView 
from django.views.generic.edit import CreateView, UpdateView 
from django.views.generic import ListView , DeleteView 
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post,Gallery# 追加
from accounts.models import Relationship, User 
from .forms import PostCreateForm, PostUpdateForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponse,JsonResponse # 追加

# Create your views here.
class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'microposts/create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('microposts:create')

    def form_valid(self, form):
        # formに問題なければ、owner id に自分のUser idを割り当てる        
        # request.userが一つのセットでAuthenticationMiddlewareでセットされている。
        form.instance.owner_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました')
        return super(PostCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました')
        return redirect('microposts:create')

class PostListView(LoginRequiredMixin, ListView):   
    # テンプレートを指定
    template_name = 'microposts/postlist.html'
    # 利用するモデルを指定
    model = Post
    # ページネーションの表示件数
    paginate_by = 3

    # Postsテーブルの全データを取得するメソッド定義
    # テンプレートでは、object_listとしてreturnの値が渡される
    def get_queryset(self):
        return Post.objects.all()  


    def get_context_data(self, **kwargs): # 追加
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['favourite_list'] = user.favourite_post.all()

        return context

class PostUpdateView(LoginRequiredMixin, UpdateView): 
    model = Post
    form_class = PostUpdateForm
    template_name = 'microposts/update.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super(PostUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('microposts:update', kwargs={'pk': self.object.id})

    def form_invalid(self, form):
        messages.warning(self.request, '更新が失敗しました')
        return reverse_lazy('microposts:update', kwargs={'pk': self.object.id})

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'microposts/delete.html'
    # deleteviewでは、SuccessMessageMixinが使われないので設定する必要あり
    success_url = reverse_lazy('microposts:create')
    success_message = "投稿は削除されました。"

    # 削除された際にメッセージが表示されるようにする。
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)

class MyPostsView(LoginRequiredMixin, ListView): 
    # テンプレートを指定
    template_name = 'microposts/myposts.html'
    # 利用するモデルを指定
    model = Post
    # ページネーションの表示件数
    paginate_by = 3

    # Postsテーブルのowner_idが自分自身の全データを取得するメソッド定義
    def get_queryset(self):  
        qs = Post.objects.filter(owner_id=self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        qs = Post.objects.filter(owner_id=self.request.user)
        # qsのレコード数をmy_posts_countというコンテキストとして設定
        context['my_posts_count'] = qs.count()
        # Postsテーブルの全データを取得しpost_listへ格納
        context['favorite_list'] = user.favourite_post.all()
        context['following_list'] = Relationship.objects.filter(follower_id=user.id)
        # 自分がfollowしているidのみをmy_follow_listとして取得
        context['my_follow_list'] = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id', flat=True)
        # 自分がフォローしている人をfollowingsとして取得
        followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
        context['following_count'] = User.objects.filter(id__in=followings).count()
        # 自分をフォローしている人をfollowersとして取得
        followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
        # context['followers_data] = User.objects.filter(id__in=followers).count()
        context['follower_count'] = followers.count()
        return context

def add_favourite(request, pk): # 追加
    # postのpkをhtmlから取得
    post = get_object_or_404(Post, pk=pk)
    # ログインユーザーを取得
    user = request.user
    # ログインユーザーをfavoritePostのUser_idとして、post_idは
    # 上で取得したPostを記録
    user.favourite_post.add(post)
    return redirect('microposts:postlist')


def remove_favourite(request, pk): # 追加
    # postのpkをhtmlから取得
    post = get_object_or_404(Post, pk=pk)
    # ログインユーザーを取得
    user = request.user
    # ログインユーザーをfavoritePostのUser_idとして、post_idは
    # 上で取得したPostを記録
    user.favourite_post.remove(post)
    return redirect('microposts:postlist')

class FollowersView(LoginRequiredMixin, ListView): # 追加
    # テンプレートを指定
    template_name = 'microposts/followers.html'
    # 利用するモデルを指定
    model = Relationship

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Postsテーブルの自分の投稿数をmy_posts_countへ格納
        context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
        # 自分がフォローしている人をfollowingsとして取得
        followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
        # 自分がフォローしている人のオブジェクトを取得
        context['following_list'] = User.objects.filter(id__in=followings)
        # 自分がフォローしている人の数を取得
        context['following_count'] = User.objects.filter(id__in=followings).count()
        # 自分をフォローしている人をfollowersとして取得
        followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
        # 自分をフォローしている人の数を取得
        context['follower_list'] = User.objects.filter(id__in=followers)
        return context


class FollowingView(LoginRequiredMixin, ListView): # 追加
    # テンプレートを指定
    template_name = 'microposts/followings.html'
    # 利用するモデルを指定
    model = Relationship

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Postsテーブルの自分の投稿数をmy_posts_countへ格納
        context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
        # 自分がフォローしている人をfollowingsとして取得
        followings = (Relationship.objects.filter(follower_id=user.id)).values_list('following_id')
        # 自分がフォローしている人のオブジェクトを取得
        context['following_list'] = User.objects.filter(id__in=followings)
        # 自分をフォローしている人をfollowersとして取得
        followers = (Relationship.objects.filter(following_id=user.id)).values_list('follower_id')
        # 自分をフォローしている人の数を取得
        context['follower_count'] = User.objects.filter(id__in=followers).count()
        return context

# file(=画像)をアップロードする関数
def add_file(request):
    if request.method == "POST":        
        # ログインユーザーを取得
        user = request.user
        # 画像をテンプレートからfileとして取得
        pict = request.FILES.get('file')
        # Galleryモデルにオーナーと画像を保存
        Gallery.objects.create(owner = user, image=pict)
        return HttpResponse('')
    return HttpResponse('post error')

class GalleryView(LoginRequiredMixin,ListView):
    template_name = 'microposts/gallery.html'
    # 利用するモデルを指定
    model = Gallery    
    
    # Galleryテーブルのowner_idが自分自身の全データを取得するqs
    def get_queryset(self):  
        qs = Gallery.objects.filter(owner_id=self.request.user)
        return qs

templates/microposts/delete.html
{% extends 'base.html' %}
{% block content %}
{#    投稿したユーザーしか削除できない制約を追加#}
    {% if object.owner_id == user.id %}
        <form method="POST">
        {% csrf_token %}
        <p>「{{ object.content }}」を削除しますか？</p>
        <button type="submit" class="btn btn-default btn-danger">
            削除する
        </button>
    </form>
        {% else %}
        <h1>{{ user.get_username }}さんの投稿ではありません。</h1>
    {% endif %}
{% endblock %}

templates/microposts/followers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <!--ページタイトル-->
                <aside class="col-sm-4">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">{{ user.get_username }}</h3>
                        </div>
                        <div class="card-body">
                            {# ユーザーがプロフィール画像を持っている場合#}
                            {% if user.avatar %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                                {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                            {% endif %}
                        </div>
                        <a class="btn btn-outline-secondary btn-sm"
                            href="{% url 'accounts:edit_profile' %}" role="button">プロフィール更新</a>
                    </div>
                </aside>
                <div class="col-sm-8">
                    <ul class="nav nav-tabs nav-justified mb-3">
                        <li class="nav-item"><a href="{% url 'microposts:myposts' %}" class="nav-link">MyPosts一覧
                            {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        {# ここから、リンク設定とBadgeの設定を変更 #}
                        <li class="nav-item"><a href="{% url 'microposts:following' %}" class="nav-link">Followings
                            {#  followings数を表示#}
                            <span class="badge badge-secondary">{{ following_count }}</span></a></li>
                        <li class="nav-item"><a href="{% url 'microposts:follower' %}" class="nav-link active">Followers
                            {#  follower数を表示し、nav-linkをActiveにする#}
                            <span class="badge badge-secondary">{{ follower_list | length }}</span></a></li>                        
                        {# ここまで、リンク設定とBadgeの設定を変更 #}
                    </ul>

                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='follower_list'
                            class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                {# 列名と幅を変更 #}
                                <th class="text-center" style="width: 50%">ユーザー</th>
                                <th class="text-center" style="width: 50%">Follow/Unfollow</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {# follower_list：自分をお気に入り登録してくれているユーザーのリスト #}
                            {% for item in follower_list %}
                                <tr class="text">
                                    <td class="text-center">{{ item.username }}</td>
                                    <td class="text-center align-middle">
                                        {# 対象ユーザーを自分もお気に入り登録している場合 #}                                        
                                        {% if item in following_list %}
                                            {# Unfollowボタンで対象ユーザーに対して、rm_relation関数を呼び出してお気に入り解除 #}  
                                            <form action="{% url 'accounts:rm_relation' pk=item.id %}" method="post">
                                                <button type="submit" class="btn btn-outline-danger btn-sm" name="button">
                                                    Unfollow
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {# 対象ユーザーを自分がお気に入り登録していない場合 #}     
                                        {% else %}
                                            <form action="{% url 'accounts:mk_relation' pk=item.id %}" method="post">
                                                <button type="submit" class="btn btn-outline-primary btn-sm" name="button">
                                                    Follow
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/followings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <!--ページタイトル-->
                <aside class="col-sm-4">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">{{ user.get_username }}</h3>
                        </div>
                        <div class="card-body">
                            {# ユーザーがプロフィール画像を持っている場合#}
                            {% if user.avatar %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                                {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                            {% endif %}
                        </div>
                        <a class="btn btn-outline-secondary btn-sm"
                            href="{% url 'accounts:edit_profile' %}" role="button">プロフィール更新</a>
                    </div>
                </aside>
                <div class="col-sm-8">
                    <ul class="nav nav-tabs nav-justified mb-3">
                        <li class="nav-item"><a href="{% url 'microposts:myposts' %}" class="nav-link">MyPosts一覧
                            {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        {# ここから、リンク設定とBadgeの設定を変更 #}
                        <li class="nav-item"><a href="{% url 'microposts:following' %}" class="nav-link active">Followings
                            {#  following数を表示し、nav-linkをActiveにする #}
                            <span class="badge badge-secondary">{{ following_list | length }}</span></a></li>
                        <li class="nav-item"><a href="{% url 'microposts:follower' %}" class="nav-link">Followers
                            {#  follower数を表示#}
                            <span class="badge badge-secondary">{{ follower_count }}</span></a></li>                        
                        {# ここまで、リンク設定とBadgeの設定を変更 #}
                    </ul>

                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='following_list'
                            class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                {# 列名と幅を変更 #}
                                <th class="text-center" style="width: 50%">ユーザー</th>
                                <th class="text-center" style="width: 50%">Follow/Unfollow</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {# following_list：お気に入り登録しているユーザーのリスト #}
                            {% for item in following_list %}
                                <tr class="text">
                                    <td class="text-center">{{ item.username }}</td>
                                    <td class="text-center align-middle">
                                        {# Unfollowボタンで対象ユーザーに対して、rm_relation関数を呼び出してお気に入り解除 #}                                        
                                        <form action="{% url 'accounts:rm_relation' pk=item.id %}" method="post">
                                                <button type="submit" class="btn btn-outline-danger btn-sm" name="button">
                                                    Unfollow
                                                </button>
                                                {% csrf_token %}
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/gallery.html
{% extends 'base.html' %}
{% block content %}
    <div class="center jumbotron">
        <div class="text-center">            
            <h2>Your Gallery</h2>
        </div>
        {# Galleryモデルの画像を表示する部分#}
        <div>
            {% for item in object_list %}
            {# magnific-popupを適用 #}
                <a class="popup" href="{{ item.image.url }}">
                <img class="rounded img-fluid mx-auto d-inline"
                    src="{{ item.image.url }}" id="gallery-thumbnail" alt="gallery-thumbnail">   
                </a>
            {% endfor %}
        </div>
        {# Galleryモデルの画像を表示する部分　ここまで #}
    </div>
    {# Dropzone.jsを用いたドラッグ＆ドロップ領域の設定 #}
    <form action="{% url 'microposts:add_file' %}" method="post" class="dropzone dz" id="my-dropzone">
            {% csrf_token %}
            <div class="fallback">
                <input name="file" type="file" multiple/>
            </div>
    </form>
    {# Dropzone.jsを用いたドラッグ＆ドロップ領域の設定 ここまで#}
{% endblock %}

templates/microposts/myposts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">        
            <div class="row">
                <!--ページタイトル-->
                <aside class="col-sm-4">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title text-center">{{ user.get_username }}</h3>
                        </div>
                        <div class="card-body">
                            {# ユーザーがプロフィール画像を持っている場合#}
                            {% if user.avatar %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                                {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                            {% endif %}
                        </div>
                        <a class="btn btn-outline-secondary btn-sm"
                            href="{% url 'accounts:edit_profile' %}" role="button">プロフィール更新</a>
                    </div>
                </aside>
                <div class="col-sm-8">
                    <ul class="nav nav-tabs nav-justified mb-3">
                        <li class="nav-item"><a href="{% url 'microposts:myposts' %}" class="nav-link active">MyPosts一覧
                            {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        {# ここから、リンク設定とBadgeの設定を変更 #}
                        <li class="nav-item"><a href="{% url 'microposts:following' %}" class="nav-link">Followings
                            {#  フォロワー数を表示#}
                            <span class="badge badge-secondary">{{ following_count }}</span></a></li>
                        <li class="nav-item"><a href="{% url 'microposts:follower' %}" class="nav-link">Followers
                            {#  フォロワー数を表示#}
                            <span class="badge badge-secondary">{{ follower_count }}</span></a></li>
                        {# ここまで、リンク設定とBadgeの設定を変更 #}
                    </ul>
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list'
                            class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center" style="width: 80%">投稿内容</th>
                                <th class="text-center" style="width: 20%">更新／削除</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text"><h6>@{{ item.created_at }}</h6>{{ item.content }}</td>
                                    <td class="text-center align-middle">
                                        {#  pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                        <a class="btn btn-outline-success btn-sm"
                                            href="{% url 'microposts:update' item.pk %}"
                                            role="button">更新</a>
                                        <a class="btn btn-outline-danger btn-sm"
                                            href="{% url 'microposts:delete' item.pk %}"
                                            role="button">削除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                    {#   django-bootstrap4のページネーション#}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/microposts/postlist.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <!--ページタイトル-->
            <div class="card mb-3">
                <div class="card-header">
                    <h4><b>投稿一覧</b></h4>
                </div>
                <div class="card-body">
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list' class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center">投稿内容</th>
                                <th class="text-center">お気に入り</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {# デフォルトはobject_listとなるが、view.pyでcontextとして指定#}
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text" style="width: 80%">
                                        <h6>{{ item.owner }}@{{ item.created_at}}</h6>{{ item.content }} 
                                        {# 投稿に画像がある場合#}    
                                        {% if item.image %}                          
                                        <img class="rounded img-fluid mx-auto d-block" src="{{ item.image.url }}" 
                                            id="post-thumbnail" alt="post-thumbnail">  
                                        {% endif %}
                                    </td>
                                    <td class="text-center align-middle" style="width: 20%">
                                        {#  pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                        {#  favorite_list に itemがあれば（すでにお気に入り登録されていれば）#}
                                        {% if item in favourite_list %}
                                            {#     <button type="button" class="btn btn-primary">登録済み</button>#}
                                            <form action="{% url 'microposts:rm_favourite' pk=item.pk %}" method="post">
                                                <button type="submit" class="btn btn-link" name="button">
                                                    <i class="fas fa-thumbs-up"></i>
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {% else %}
                                            {#  object_listの要素をitemとして取り出しているので、item.pkでpk取得#}
                                            <form action="{% url 'microposts:add_favourite' pk=item.pk %}" method="post">
                                                <button type="submit" class="btn btn-link" name="button">
                                                    <i class="far fa-thumbs-up"></i>
                                                </button>
                                                {% csrf_token %}
                                            </form>
                                        {% endif %}
                                    </td>                                  
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                    {#   django-bootstrap4のページネーション#}
                    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}